### ISSUE TITLE
 Property TileWMS never defined on ol.source

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#581]
After a rebase I get this error, that a clean does not fix : 

ERR! compile /var/www/vhosts/geoportailv3_mire/node_modules/ngeo/src/services/print.js:315: ERROR - Property TileWMS never defined on ol.source
ERR! compile   goog.asserts.assertInstanceof(source, ol.source.TileWMS);
ERR! compile                                                   ^
ERR! compile
ERR! compile 1 error(s), 0 warning(s), 97.2
ERR! compile % typed
ERR! compile

**Comment by elemoine** [comment]
Did you just reinstall ngeo?

**Comment by elemoine** [comment]
Ok I think I know what the problem is. ngeo PR to come…

**Comment by rmichaelis** [comment]
Ok Thanks :-)

**Comment by elemoine** [comment]
https://github.com/camptocamp/ngeo/pull/242 should fix it.

**Comment by elemoine** [comment]
It should be fixed now.

**Comment by rmichaelis** [comment]
It works. Thanks
